### ISSUE TITLE
Feature Request: Support for Expo 54 and React Native 0.81 (New Architecture)

### ISSUE THREAD

**Issue by onoff0994-oss** [volga-volga/react-native-yamap#337]
Description
I am currently developing a professional ride-hailing app and am unable to upgrade to Expo 54 and React Native 0.81. Since Yandex Maps is the only thing that is interesting and viable for our business model, it is essential to have a stable version for the latest Expo SDK.

Current Issues
The library currently fails to compile or run on Expo 54 due to several breaking changes in the React Native ecosystem:

Removal of currentActivity: Following the upgrade to RN 0.81, the currentActivity method has been deprecated/removed in the core. The native Android implementation of react-native-yamap still relies on this, causing immediate runtime crashes.

Kotlin & Gradle Version Mismatch: Expo 54 requires Kotlin 2.1.20 and Target SDK 36. The current library setup triggers compilation errors (e.g., compileDebugKotlin failures) because it doesn't align with these newer build tools.

New Architecture (Fabric/TurboModules): Expo 54 is moving towards full adoption of the New Architecture. We need a version that supports Bridgeless mode and does not rely on outdated native hooks.

Missing Config Plugin: To avoid manual changes in the android/ and ios/ folders (which is discouraged in the Expo managed workflow), a robust Expo Config Plugin is needed to handle the API key injection and initialization.

Environment

Expo SDK: 54.x

React Native: 0.81.x

Platform: Android (Primary) & iOS

Build Tool: EAS Build / npx expo prebuild

Expected Behavior
The library should compile successfully with npx expo prebuild using Kotlin 2.1.x and should not crash upon calling YaMap.init() due to missing activity references.

Additional Context
Many VTC startups are looking for this update because Google Maps' pricing is unsustainable for high-volume taxi services. Any guidance, private branch, or alpha release for testing would be greatly appreciated.

**Comment by onoff0994-oss** [comment]
"Hi @raxenov, @volga-volga — I've just opened this issue because we are currently stuck on our VTC project due to the Expo 54 / RN 0.81 breaking changes. Many of us in the community are looking for a fix regarding the currentActivity removal and Kotlin 2.1 compatibility. Could you please take a look or let us know if a roadmap for this update exists? Thanks!"

**Comment by Bolikus** [comment]
> "Hi @raxenov, [@volga-volga](https://github.com/volga-volga) — I've just opened this issue because we are currently stuck on our VTC project due to the Expo 54 / RN 0.81 breaking changes. Many of us in the community are looking for a fix regarding the currentActivity removal and Kotlin 2.1 compatibility. Could you please take a look or let us know if a roadmap for this update exists? Thanks!"

Do you try this one? It's a fork of this library:
https://github.com/Qudaeo/react-native-yamap-plus

**Comment by onoff0994-oss** [comment]
thanks good
